website/views.py
import json
from flask import Blueprint, render_template , request, redirect, url_for , session , jsonify , flash
from datetime import timedelta
from flask_paginate import Pagination, get_page_parameter
import psycopg2
import boto3
import os
import itertools
import ast
views = Blueprint('views', __name__)
# db_params = {
#     'dbname': 'postgres',
#     'user': 'postgres',
#     'password': 'postgres',
#     'host': 'bookstore.cshzuj1alait.eu-north-1.rds.amazonaws.com',
#     'port': '5432'
# }
db_params = {
    'dbname': 'postgres',
    'user': 'postgres',
    'password': 'postgres',
    'host': 'ksiengarnia-db.cshzuj1alait.eu-north-1.rds.amazonaws.com',
    'port': '5432'
}
# Shopping_list = list()
lambda_client = boto3.client('lambda', region_name='eu-north-1')



swear_words = ['chuj','chuja', 'chujek', 'chuju', 'chujem', 'chujnia',
'chujowy', 'chujowa', 'chujowe', 'cipa', 'cipę', 'cipe', 'cipą',
'cipie', 'dojebać','dojebac', 'dojebie', 'dojebał', 'dojebal',
'dojebała', 'dojebala', 'dojebałem', 'dojebalem', 'dojebałam',
'dojebalam', 'dojebię', 'dojebie', 'dopieprzać', 'dopieprzac',
'dopierdalać', 'dopierdalac', 'dopierdala', 'dopierdalał',
'dopierdalal', 'dopierdalała', 'dopierdalala', 'dopierdoli',
'dopierdolił', 'dopierdolil', 'dopierdolę', 'dopierdole', 'dopierdoli',
'dopierdalający', 'dopierdalajacy', 'dopierdolić', 'dopierdolic',
'dupa', 'dupie', 'dupą', 'dupcia', 'dupeczka', 'dupy', 'dupe', 'huj',
'hujek', 'hujnia', 'huja', 'huje', 'hujem', 'huju', 'jebać', 'jebac',
'jebał', 'jebal', 'jebie', 'jebią', 'jebia', 'jebak', 'jebaka', 'jebal',
'jebał', 'jebany', 'jebane', 'jebanka', 'jebanko', 'jebankiem',
'jebanymi', 'jebana', 'jebanym', 'jebanej', 'jebaną', 'jebana',
'jebani', 'jebanych', 'jebanymi', 'jebcie', 'jebiący', 'jebiacy',
'jebiąca', 'jebiaca', 'jebiącego', 'jebiacego', 'jebiącej', 'jebiacej',
'jebia', 'jebią', 'jebie', 'jebię', 'jebliwy', 'jebnąć', 'jebnac',
'jebnąc', 'jebnać', 'jebnął', 'jebnal', 'jebną', 'jebna', 'jebnęła',
'jebnela', 'jebnie', 'jebnij', 'jebut', 'koorwa', 'kórwa', 'kurestwo',
'kurew', 'kurewski', 'kurewska', 'kurewskiej', 'kurewską', 'kurewska',
'kurewsko', 'kurewstwo', 'kurwa', 'kurwaa', 'kurwami', 'kurwą', 'kurwe',
'kurwę', 'kurwie', 'kurwiska', 'kurwo', 'kurwy', 'kurwach', 'kurwami',
'kurewski', 'kurwiarz', 'kurwiący', 'kurwica', 'kurwić', 'kurwic',
'kurwidołek', 'kurwik', 'kurwiki', 'kurwiszcze', 'kurwiszon',
'kurwiszona', 'kurwiszonem', 'kurwiszony', 'kutas', 'kutasa', 'kutasie',
'kutasem', 'kutasy', 'kutasów', 'kutasow', 'kutasach', 'kutasami',
'matkojebca', 'matkojebcy', 'matkojebcą', 'matkojebca', 'matkojebcami',
'matkojebcach', 'nabarłożyć', 'najebać', 'najebac', 'najebał',
'najebal', 'najebała', 'najebala', 'najebane', 'najebany', 'najebaną',
'najebana', 'najebie', 'najebią', 'najebia', 'naopierdalać',
'naopierdalac', 'naopierdalał', 'naopierdalal', 'naopierdalała',
'naopierdalala', 'naopierdalała', 'napierdalać', 'napierdalac',
'napierdalający', 'napierdalajacy', 'napierdolić', 'napierdolic',
'nawpierdalać', 'nawpierdalac', 'nawpierdalał', 'nawpierdalal',
'nawpierdalała', 'nawpierdalala', 'obsrywać', 'obsrywac', 'obsrywający',
'obsrywajacy', 'odpieprzać', 'odpieprzac', 'odpieprzy', 'odpieprzył',
'odpieprzyl', 'odpieprzyła', 'odpieprzyla', 'odpierdalać',
'odpierdalac', 'odpierdol', 'odpierdolił', 'odpierdolil',
'odpierdoliła', 'odpierdolila', 'odpierdoli', 'odpierdalający',
'odpierdalajacy', 'odpierdalająca', 'odpierdalajaca', 'odpierdolić',
'odpierdolic', 'odpierdoli', 'odpierdolił', 'opieprzający',
'opierdalać', 'opierdalac', 'opierdala', 'opierdalający',
'opierdalajacy', 'opierdol', 'opierdolić', 'opierdolic', 'opierdoli',
'opierdolą', 'opierdola', 'piczka', 'pieprznięty', 'pieprzniety',
'pieprzony', 'pierdel', 'pierdlu', 'pierdolą', 'pierdola', 'pierdolący',
'pierdolacy', 'pierdoląca', 'pierdolaca', 'pierdol', 'pierdole',
'pierdolenie', 'pierdoleniem', 'pierdoleniu', 'pierdolę', 'pierdolec',
'pierdola', 'pierdolą', 'pierdolić', 'pierdolicie', 'pierdolic',
'pierdolił', 'pierdolil', 'pierdoliła', 'pierdolila', 'pierdoli',
'pierdolnięty', 'pierdolniety', 'pierdolisz', 'pierdolnąć',
'pierdolnac', 'pierdolnął', 'pierdolnal', 'pierdolnęła', 'pierdolnela',
'pierdolnie', 'pierdolnięty', 'pierdolnij', 'pierdolnik', 'pierdolona',
'pierdolone', 'pierdolony', 'pierdołki', 'pierdzący', 'pierdzieć',
'pierdziec', 'pizda', 'pizdą', 'pizde', 'pizdę', 'piździe', 'pizdzie',
'pizdnąć', 'pizdnac', 'pizdu', 'podpierdalać', 'podpierdalac',
'podpierdala', 'podpierdalający', 'podpierdalajacy', 'podpierdolić',
'podpierdolic', 'podpierdoli', 'pojeb', 'pojeba', 'pojebami',
'pojebani', 'pojebanego', 'pojebanemu', 'pojebani', 'pojebany',
'pojebanych', 'pojebanym', 'pojebanymi', 'pojebem', 'pojebać',
'pojebac', 'pojebalo', 'popierdala', 'popierdalac', 'popierdalać',
'popierdolić', 'popierdolic', 'popierdoli', 'popierdolonego',
'popierdolonemu', 'popierdolonym', 'popierdolone', 'popierdoleni',
'popierdolony', 'porozpierdalać', 'porozpierdala', 'porozpierdalac',
'poruchac', 'poruchać', 'przejebać', 'przejebane', 'przejebac',
'przyjebali', 'przepierdalać', 'przepierdalac', 'przepierdala',
'przepierdalający', 'przepierdalajacy', 'przepierdalająca',
'przepierdalajaca', 'przepierdolić', 'przepierdolic', 'przyjebać',
'przyjebac', 'przyjebie', 'przyjebała', 'przyjebala', 'przyjebał',
'przyjebal', 'przypieprzać', 'przypieprzac', 'przypieprzający',
'przypieprzajacy', 'przypieprzająca', 'przypieprzajaca',
'przypierdalać', 'przypierdalac', 'przypierdala', 'przypierdoli',
'przypierdalający', 'przypierdalajacy', 'przypierdolić',
'przypierdolic', 'qrwa', 'rozjebać', 'rozjebac', 'rozjebie',
'rozjebała', 'rozjebią', 'rozpierdalać', 'rozpierdalac', 'rozpierdala',
'rozpierdolić', 'rozpierdolic', 'rozpierdole', 'rozpierdoli',
'rozpierducha', 'skurwić', 'skurwiel', 'skurwiela', 'skurwielem',
'skurwielu', 'skurwysyn', 'skurwysynów', 'skurwysynow', 'skurwysyna',
'skurwysynem', 'skurwysynu', 'skurwysyny', 'skurwysyński',
'skurwysynski', 'skurwysyństwo', 'skurwysynstwo', 'spieprzać',
'spieprzac', 'spieprza', 'spieprzaj', 'spieprzajcie', 'spieprzają',
'spieprzaja', 'spieprzający', 'spieprzajacy', 'spieprzająca',
'spieprzajaca', 'spierdalać', 'spierdalac', 'spierdala', 'spierdalał',
'spierdalała', 'spierdalal', 'spierdalalcie', 'spierdalala',
'spierdalający', 'spierdalajacy', 'spierdolić', 'spierdolic',
'spierdoli', 'spierdoliła', 'spierdoliło', 'spierdolą', 'spierdola',
'srać', 'srac', 'srający', 'srajacy', 'srając', 'srajac', 'sraj',
'sukinsyn', 'sukinsyny', 'sukinsynom', 'sukinsynowi', 'sukinsynów',
'sukinsynow', 'śmierdziel', 'udupić', 'ujebać', 'ujebac', 'ujebał',
'ujebal', 'ujebana', 'ujebany', 'ujebie', 'ujebała', 'ujebala',
'upierdalać', 'upierdalac', 'upierdala', 'upierdoli', 'upierdolić',
'upierdolic', 'upierdoli', 'upierdolą', 'upierdola', 'upierdoleni',
'wjebać', 'wjebac', 'wjebie', 'wjebią', 'wjebia', 'wjebiemy',
'wjebiecie', 'wkurwiać', 'wkurwiac', 'wkurwi', 'wkurwia', 'wkurwiał',
'wkurwial', 'wkurwiający', 'wkurwiajacy', 'wkurwiająca', 'wkurwiajaca',
'wkurwić', 'wkurwic', 'wkurwi', 'wkurwiacie', 'wkurwiają', 'wkurwiali',
'wkurwią', 'wkurwia', 'wkurwimy', 'wkurwicie', 'wkurwiacie', 'wkurwić',
'wkurwic', 'wkurwia', 'wpierdalać', 'wpierdalac', 'wpierdalający',
'wpierdalajacy', 'wpierdol', 'wpierdolić', 'wpierdolic', 'wpizdu',
'wyjebać', 'wyjebac', 'wyjebali', 'wyjebał', 'wyjebac', 'wyjebała',
'wyjebały', 'wyjebie', 'wyjebią', 'wyjebia', 'wyjebiesz', 'wyjebie',
'wyjebiecie', 'wyjebiemy', 'wypieprzać', 'wypieprzac', 'wypieprza',
'wypieprzał', 'wypieprzal', 'wypieprzała', 'wypieprzala', 'wypieprzy',
'wypieprzyła', 'wypieprzyla', 'wypieprzył', 'wypieprzyl', 'wypierdal',
'wypierdalać', 'wypierdalac', 'wypierdala', 'wypierdalaj',
'wypierdalał', 'wypierdalal', 'wypierdalała', 'wypierdalala',
'wypierdalać', 'wypierdolić', 'wypierdolic', 'wypierdoli',
'wypierdolimy', 'wypierdolicie', 'wypierdolą', 'wypierdola',
'wypierdolili', 'wypierdolił', 'wypierdolil', 'wypierdoliła',
'wypierdolila', 'zajebać', 'zajebac', 'zajebie', 'zajebią', 'zajebia',
'zajebiał', 'zajebial', 'zajebała', 'zajebiala', 'zajebali', 'zajebana',
'zajebani', 'zajebane', 'zajebany', 'zajebanych', 'zajebanym',
'zajebanymi', 'zajebiste', 'zajebisty', 'zajebistych', 'zajebista',
'zajebistym', 'zajebistymi', 'zajebiście', 'zajebiscie', 'zapieprzyć',
'zapieprzyc', 'zapieprzy', 'zapieprzył', 'zapieprzyl', 'zapieprzyła',
'zapieprzyla', 'zapieprzą', 'zapieprza', 'zapieprzy', 'zapieprzymy',
'zapieprzycie', 'zapieprzysz', 'zapierdala', 'zapierdalać',
'zapierdalac', 'zapierdalaja', 'zapierdalał', 'zapierdalaj',
'zapierdalajcie', 'zapierdalała', 'zapierdalala', 'zapierdalali',
'zapierdalający', 'zapierdalajacy', 'zapierdolić', 'zapierdolic',
'zapierdoli', 'zapierdolił', 'zapierdolil', 'zapierdoliła',
'zapierdolila', 'zapierdolą', 'zapierdola', 'zapierniczać',
'zapierniczający', 'zasrać', 'zasranym', 'zasrywać', 'zasrywający',
'zesrywać', 'zesrywający', 'zjebać', 'zjebac', 'zjebał', 'zjebal',
'zjebała', 'zjebala', 'zjebana', 'zjebią', 'zjebali', 'zjeby']




@views.route('/')
def home():
    # if "user" in session:
    #     with psycopg2.connect(**db_params) as connection:
    #                 with connection.cursor() as cursor:
    #                     query = "SELECT COUNT(ksiazka_id) FROM koszyk WHERE klient_id = %s"
    #                     cursor.execute(query, (str(session["user"])))
    #                     koszyk = cursor.fetchall()
    #                     session["koszyk"] = koszyk[0][0];   
    return render_template('base.html')

@views.route('/ksiazki')
def books():
    page = request.args.get(get_page_parameter(), type=int, default=1)
    per_page = 16
    offset = (page - 1) * per_page
    
    connection = psycopg2.connect(**db_params)
    cursor = connection.cursor()
    query = """
    SELECT * FROM ksiazki
    ORDER BY ksiazka_id
    LIMIT %s OFFSET %s
    """
    cursor.execute(query, (per_page, offset))
    results = cursor.fetchall()
    cursor.execute("SELECT COUNT(*) FROM ksiazki")
    total_records = cursor.fetchone()[0]

website/templates/about_us.html
{% extends "base.html" %}
{% block title %}O nas{% endblock %}
{% block content %}
<h1>O NAS</h1>
<h2>Przędziemy Historię Literatury</h2>
<h5>Witajcie w magicznym świecie słów, gdzie każda strona jest bramą do niezliczonych przygód literackich. Nasza księgarnia internetowa powstała z pasji do czytania, miłości do literatury i pragnienia dzielenia się tą fascynacją z Wami, naszymi czytelnikami.</h5>
<h2>Kim Jesteśmy?</h2>
<h5>Jesteśmy zespołem entuzjastów literatury, skupionych na tworzeniu wyjątkowego miejsca online, gdzie każdy może znaleźć coś dla siebie. Nasza historia zaczęła się od marzenia o stworzeniu przestrzeni, w której książki stają się mostem łączącym ludzi, miejscem, gdzie czytelnicy mogą odkrywać nowe światy i doświadczać różnorodności literackiego krajobrazu.</h5>
<h2>Dlaczego Księgarnia Internetowa?</h2>
<h5>W erze cyfrowej postanowiliśmy przekroczyć granice tradycyjnych księgarń, aby dostarczyć Wam nieograniczone możliwości odkrywania literatury. Nasza księgarnia internetowa oferuje szeroki wybór tytułów, począwszy od klasyki, poprzez bestsellery, aż po perełki literatury niezależnej. Dzięki prostocie nawigacji, możecie podróżować między stronami książek, odkrywać nowe autorów i zgłębiać tajniki różnych gatunków literackich.</h5>
<h2>Misja, którą Przynosimy</h2>
<h5>Naszą misją jest nie tylko dostarczanie Wam fascynujących książek, ale także budowanie społeczności czytelników, którzy dzielą tę samą pasję. Organizujemy wydarzenia online, książkowe kluby czytelnicze i udostępniamy przestrzeń do dzielenia się Waszymi recenzjami i spostrzeżeniami. Wierzymy, że literatura ma moc łączenia ludzi i inspiracji, a my chcemy być miejscem, gdzie ta magia się spełnia.</h5>
<h2>Nasi Partnerzy</h2>
<h5>Współpracujemy z autorami, wydawnictwami i innymi instytucjami literackimi, aby nasza oferta była zawsze świeża i zróżnicowana. Dzięki tym współpracom możemy dostarczać Wam unikalne tytuły, których nie znajdziecie w innych miejscach.</h5>
<h2>Wspólna Podróż przez Strony Książek</h2>
<h5>Zapraszamy Was do wspólnej podróży przez świat literatury. Niech nasza księgarnia internetowa stanie się dla Was miejscem, gdzie odkryjecie nie tylko nowe książki, ale także nowych przyjaciół i inspiracje do kolejnych literackich podróży.</h5>

{%endblock%}


<br>
<div class="col mb-5">
    <div class="card h-100">
        <!-- Product details-->
        <div class="card-body p-4">
            <div class="text-center">
                <h2>Dodaj Komentarz</h2>
                    <form>
                        <div class="form-group">
                        <label for="komentarz">Treść Komentarza:</label>
                        <textarea class="form-control" id="komentarz" rows="4" placeholder="Wprowadź swój komentarz"></textarea>
                        </div>
                        <div class="form-group">
                        <label for="ocena">Ocena (od 1 do 5):</label>
                        <input type="number" class="form-control" id="ocena" min="1" max="5" placeholder="Wprowadź ocenę">
                        </div>
                        <button type="submit" class="btn btn-primary">Dodaj Komentarz</button>
                    </form>
            </div>
        </div>
        <!-- Product actions-->
        <div class="text-center">
        <h6>{{row[1]}}</h6>
        </div>  
        <br>
    </div>
</div>

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <title>{% block title %}Bookstore{% endblock %}</title>
        <link href="{{ url_for('static', filename='css/styles.css' )}}" rel="stylesheet" />
        <style>
            .background-image {
                width: 100%;
                height: 100%;
                object-fit: cover;
                filter: blur(5px);
            }
            .text-container {
                padding: 20px;
                background-color: #f8f9fa;
                border-radius: 5px;
                box-shadow: 0 4px 8px rgba(0,0,0,0.1);
            }

            .text-container h2 {
                color: #333;
                margin-bottom: 15px;
            }

            .text-container p {
                color: #666;
                line-height: 1.6;
            }
            .star {
                color: darkorange;
                cursor: pointer;
                font-size: 30px;
            }
            .star.selected {
                color: gold;
            }

            
        </style>
        {% block csss %}{% endblock %}
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">Księgarnia</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/">Strona Główna</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('views.about_us') }}">O nas</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Sklep</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{{ url_for('views.books') }}">Produkty</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.bestsellery') }}">Bestsellery</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.naj_oceniane') }}">Nawyżej oceniane</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form method="post" class="d-flex" style="margin-right: 10px;" action="{{url_for('views.wyszukiwanie')}}">
                        <input class="form-control me-2" type="search" placeholder="szukaj"  id="szukaj" name="szukaj">
                        <button class="btn btn-outline-success" type="submit">Szukaj</button>
                    </form>
                    <form class="d-flex">
                        {%if session['user']%}
                        <a href="{{url_for('user.koszyk')}}">
                        <div class="btn btn-outline-dark">
                            <i class="bi-cart-fill me-1"></i>
                            Koszyk
                            <span class="badge bg-dark text-white ms-1 rounded-pill" type="submit" ></span>
                        </div>
                        </a>
                        <a href="{{ url_for('user.profil')}}" style="text-decoration: None;color:black">
                        <div class="btn btn-outline-dark"style="margin-left: 10px;">
                            Profil
                        </div>
                        </a>
                        <a href="{{ url_for('user.logout')}}" style="text-decoration: None;color:black">
                        <div class="btn btn-outline-dark"style="margin-left: 10px;">
                            Wyloguj
                        </div>
                        </a>
                        




                        {%else%}
                        <a href="{{ url_for('user.login')}}" style="text-decoration: None;color:black">
                        <div class="btn btn-outline-dark"style="margin-left: 10px;">
                            Logowanie
                        </div>
                        </a>
                        <a href="{{ url_for('user.sign_up')}}" style="text-decoration: None;color:black">
                        <div class="btn btn-outline-dark"style="margin-left: 10px;">
                            Rejestracja
                        </div>
                        </a>
                        {%endif%}
                        
                    </form>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark" style="padding-bottom: 0;padding-top: 0;">
            <!-- <img src="https://i.imgur.com/nVy9qD8.png" onerror="this.style.display='none'" style="width:100%;margin:0;padding:0;max-height: 400px;"> -->
            </div>
        </header>
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5" style="min-height: 800px;"> 
                <!-- <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center"> -->
                    {%block content%}
                    <div class="container mt-4">
                        <div class="row">
                    
                            <!-- Duże zdjęcie po lewej stronie https://cdn.biznesfinder.pl/f-34429-jak-dziala-ksiegarnia-internetowa.jpg-->
                            <div class="col-md-12">
                                <center><h2>Księgarnia Internetowa</h2>
                                <img class="img-fluid rounded" src="static\Images\banner.png" alt="Księgarnia"></center>
                                <br>
                            </div>
                    
                            <!-- Treść po prawej stronie -->
                            <div class="col-md-12">
                                <div class="text-container">
                                    
                                    <p>Szanowni Miłośnicy Piękna Literatury,

                                        Mamy przyjemność przedstawić Wam najnowszą perełkę literacką, której nie możecie przegapić! "Migoczące Marzenia" autorstwa utalentowanej pisarki Anna Nowak to podróż pełna emocji, wrażeń i inspiracji, która przeniesie Was do niezwykłego świata, gdzie każda strona kryje w sobie tajemnicę, a każde zdanie wciągnie Was głębiej w wir historii.
                                        
                                        Dlaczego warto zainwestować w tę wyjątkową książkę?
                                        
                                        Poruszająca Fabuła: "Migoczące Marzenia" to opowieść o miłości, determinacji i sile ludzkiego ducha. Anna Nowak mistrzowsko snuje wątki, łącząc je w pełną napięcia historię, która zatrzyma Wasze serce i jednocześnie wzbudzi fale emocji.
                                        
                                        Wyjątkowe Postaci: Autorka stworzyła niezapomniane postaci, które stają się bliskie czytelnikom. Ich rozwój, tajemnice i relacje poruszają tematy uniwersalne, sprawiając, że z łatwością odnajdziecie się w ich świecie.
                                        
                                        Mądra Sztuka Opowiadania: Anna Nowak nie tylko bawi się słowem, ale również posługuje się mądrością życiową, przemyśleniami i refleksjami, które sprawiają, że lektura nabiera głębszego znaczenia. To więcej niż zwykła książka - to intelektualna uczta.
                                        
                                        Piękne Wydanie: "Migoczące Marzenia" to nie tylko treść, ale również forma. Książka została wydana z najwyższą dbałością o detale, a jej okładka stanowi prawdziwe dzieło sztuki, które ozdobi Waszą biblioteczkę.
                                        
                                        Recenzje czytelników: Społeczność czytelników już teraz gorąco poleca tę książkę! Opinie pełne entuzjazmu potwierdzają, że "Migoczące Marzenia" to lektura, która zostaje w pamięci na długo po jej przeczytaniu.
                                        
                                        Zapraszamy Was do zakupu "Migoczących Marzeń" w naszej internetowej księgarni. To nie tylko inwestycja w fascynującą lekturę, ale także w chwilę relaksu, rozrywki i rozwijania swoich literackich zainteresowań.
                                        
                                        Nie czekajcie, odkryjcie nowy świat literatury razem z "Migoczącymi Marzeniami" już dziś!</p>
                                    <a class="btn btn-primary" href="#link-do-ksiegarni">Kup Teraz</a>
                                </div>
                            </div>
                    
                        </div>
                    </div>
                    {%endblock%}
                <!-- </div> -->
                
            </div>
        </section>
        
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container">
                
                
                <p class="m-0 text-center text-white">&copy; 2023 Księgarnia Internetowa</p>
                <p class="m-0 text-center text-white">Adres: ul. Przykładowa 123, 00-000 Warszawa</p>
                <p class="m-0 text-center text-white">Telefon: (12) 345-678-90</p>
                <p class="m-0 text-center text-white">Email: info@ksiegarniainternetowa.pl</p>
            
            
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{{ url_for('static', filename='js/scripts.js' )}}"></script>
    </body>
</html>

website/templates/bestsellers.html
{% extends "base.html" %}
{% block title %}Książki{% endblock %}
{% block content %}
<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
{%for row in results%}
<div class="col mb-5">
    <div class="card h-100">
        <!-- Product image-->
        <img class="card-img-top" src="{{ url_for('static', filename='Images/' + row[6] )}}" alt="..." />
        <!-- Product details-->
        <div class="card-body p-4">
            <div class="text-center">
                <!-- Product name-->
                <h5 class="fw-bolder">{{row[2]}}</h5>
                <!-- Product price-->
                {{row[5]}}
                <br>
                {{row[4]}}
            </div>
        </div>
        <!-- Product actions-->
        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{ url_for('views.item', item_info=row[0]) }}">Wyświetl</a></div>
        </div>
    </div>
</div>
{%endfor%}
<!-- Paginacja -->
<!-- <div class="pagination" style="height:5%;width:100%;margin: 0 auto;padding: auto"> -->
<div class="container-fluid">   
    {{ pagination.links }}
</div>



</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Rejestracja{% endblock %} {% block
content %}
<form method="POST" name="login">
  <h3>Logowanie</h3>
  <div class="form-group">
    <label for="email">Adres E-mail</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Wprowadź email"
    />
  </div>
  <div class="form-group">
    <label for="haslo1">Hasło</label>
    <input
      type="password"
      class="form-control"
      id="haslo1"
      name="haslo1"
      placeholder="Wprowadź hasło"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Logowanie</button>
</form>
{% endblock %}